# GameHelper debug configuration
monitor: ETW
startup:
  autoStartMonitor: false
  launchOnStartup: false
games:
  - dataKey: cheatengine
    executable: Cheat Engine.exe
    displayName: Cheat Engine
    enabled: true
    hdr: true
  - dataKey: project_plague
    executable: Project_Plague.exe
    displayName: Project Plague
    enabled: true
    hdr: false
  - dataKey: talesofarise
    executable: Tales of Arise.exe
    displayName: Tales of Arise
    enabled: true
    hdr: false
